Add optional Thanos Integration (#3531)
* add optional Thanos integration to Prometheus chart

* do not enable Thanos by default as it requires explicit storage configuration

* remove leftovers

* define anti affinities to spread out Thanos components

* explain why we created a headless service

* simplify naming

* bump version

* allow more flexible Prometheus configuration in Grafana

* use the latest thanos version

* bump Grafana chart version

* make Promtheus scrape Thanos components, define alerting rules

* rename scraping config

* update to Thanos 0.5.0

* update to Thanos 0.5.0

* cleanup dead compaction leftovers when starting Prometheus

* fix bad command line when backups are disabled

* do not wait forever for the config file

diff --git a/config/monitoring/prometheus/templates/statefulset.yaml b/config/monitoring/prometheus/templates/statefulset.yaml
--- a/config/monitoring/prometheus/templates/statefulset.yaml
+++ b/config/monitoring/prometheus/templates/statefulset.yaml
@@ -8,14 +8,19 @@ spec:
   revisionHistoryLimit: 10
   selector:
     matchLabels:
-      app: '{{ template "name" . }}'
+      app: {{ template "name" . }}
   serviceName: '{{ template "name" . }}'
   updateStrategy:
     type: RollingUpdate
   template:
     metadata:
       labels:
-        app: '{{ template "name" . }}'
+        app: {{ template "name" . }} # deprecated
+        app.kubernetes.io/name: prometheus
+        app.kubernetes.io/instance: {{ template "name" . }}
+        {{- if .Values.prometheus.thanos.enabled }}
+        thanos.io/store-api: 'true'
+        {{- end }}
       annotations:
         kubermatic/scrape: 'true'
         kubermatic/scrape_port: '9090'
@@ -29,25 +34,53 @@ spec:
       containers:
       - name: prometheus
         image: 'quay.io/prometheus/prometheus:{{ .Values.prometheus.version }}'
+        command: [/bin/sh]
         args:
-        - --config.file=/etc/prometheus/config/prometheus.yaml
-        - --storage.tsdb.no-lockfile
-        - --storage.tsdb.path=/var/prometheus/data
-        {{- with .Values.prometheus.tsdb.retentionTime }}
-        - --storage.tsdb.retention.time={{ . }}
-        {{- end }}
-        {{- with .Values.prometheus.tsdb.minBlockDuration }}
-        - --storage.tsdb.min-block-duration={{ . }}
-        {{- end }}
-        {{- with .Values.prometheus.tsdb.maxBlockDuration }}
-        - --storage.tsdb.max-block-duration={{ . }}
-        {{- end }}
-        - --web.enable-lifecycle
-        - --web.external-url=https://{{ .Values.prometheus.host | trim }}
-        - --web.route-prefix=/
-        {{- if .Values.prometheus.backup.enabled }}
-        - --web.enable-admin-api
-        {{- end }}
+        - -c
+        - |
+          set -euo pipefail
+
+          echo "Cleaning up block compaction leftovers..."
+          find /var/prometheus/data -type d -name '*.tmp' -maxdepth 1 -print -exec rm -r {} \;
+
+          {{- if .Values.prometheus.thanos.enabled }}
+          config=/etc/prometheus-shared/prometheus.yaml
+
+          echo "Waiting up to 60 seconds for $config..."
+          for i in $(seq 60); do
+            [ -f $config ] && break
+            sleep 1
+          done
+
+          if [ ! -f $config ]; then
+            echo "File does not exist, giving up. Check the Thanos sidecar for possible errors."
+            exit 1
+          fi
+
+          echo "Configuration found, starting Prometheus..."
+          exec /bin/prometheus \
+            --config.file=$config \
+            --storage.tsdb.no-lockfile \
+            --storage.tsdb.path=/var/prometheus/data \
+            --storage.tsdb.retention.time={{ .Values.prometheus.tsdb.retentionTime | default "24h" }} \
+            --storage.tsdb.min-block-duration=2h \
+            --storage.tsdb.max-block-duration=2h \
+            --web.enable-lifecycle \
+            --web.external-url=https://{{ .Values.prometheus.host | trim }} \
+            --web.enable-admin-api
+          {{- else }}
+          echo "Starting Prometheus..."
+          exec /bin/prometheus \
+            --config.file=/etc/prometheus/config/prometheus.yaml \
+            --storage.tsdb.no-lockfile \
+            --storage.tsdb.path=/var/prometheus/data \
+            --storage.tsdb.retention.time={{ .Values.prometheus.tsdb.retentionTime | default "24h" }} \
+            --web.enable-lifecycle \
+            {{- if .Values.prometheus.backup.enabled }}
+            --web.enable-admin-api \
+            {{- end }}
+            --web.external-url=https://{{ .Values.prometheus.host | trim }}
+          {{- end }}
         env:
         # prevent excessive memory usage until Prometheus 2.10
         - name: GODEBUG
@@ -76,9 +109,15 @@ spec:
         resources:
 {{ toYaml .Values.prometheus.containers.prometheus.resources | indent 10 }}
         volumeMounts:
+        {{- if .Values.prometheus.thanos.enabled }}
+        - name: config-shared
+          mountPath: /etc/prometheus-shared/
+          readOnly: false
+        {{- else }}
         - name: config
           mountPath: /etc/prometheus/config/
           readOnly: false
+        {{- end }}
         - name: rules
           mountPath: /etc/prometheus/rules/
           readOnly: false
@@ -94,6 +133,7 @@ spec:
         {{- end }}
         {{- end }}
 
+      {{- if not .Values.prometheus.thanos.enabled }}
       - name: reloader
         image: jimmidyson/configmap-reload
         args:
@@ -116,6 +156,7 @@ spec:
           readOnly: true
         {{- end }}
         {{- end }}
+      {{- end }}
 
       {{- if .Values.prometheus.backup.enabled }}
       - name: backup
@@ -137,6 +178,46 @@ spec:
           runAsUser: 0
         resources:
 {{ toYaml .Values.prometheus.containers.backup.resources | indent 10 }}
+      {{- end }}
+
+      {{- if .Values.prometheus.thanos.enabled }}
+      - name: thanos
+        image: '{{ .Values.prometheus.thanos.image.repository }}:{{ .Values.prometheus.thanos.image.tag }}'
+        args:
+        - sidecar
+        - --tsdb.path=/prometheus
+        - --prometheus.url=http://localhost:9090
+        - --objstore.config-file=/etc/thanos/objstore.yaml
+        - --reloader.config-file=/etc/prometheus/config/prometheus.yaml
+        - --reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yaml
+        # New flag for migrating old blocks.
+        #- --shipper.upload-compacted-once
+        env:
+        - name: POD_NAME
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.name
+        ports:
+        - name: http-sidecar
+          containerPort: 10902
+        - name: grpc
+          containerPort: 10901
+        volumeMounts:
+        - name: db
+          mountPath: /prometheus
+          readOnly: false
+          subPath: prometheus-db
+        - name: config-shared
+          mountPath: /etc/prometheus-shared
+        - name: config
+          mountPath: /etc/prometheus/config
+        - name: thanos
+          mountPath: /etc/thanos
+        securityContext:
+          runAsNonRoot: false
+          runAsUser: 0
+        resources:
+{{ toYaml .Values.prometheus.containers.thanosSidecar.resources | indent 10 }}
       {{- end }}
 
       serviceAccountName: '{{ template "name" . }}'
@@ -166,6 +247,13 @@ spec:
       {{- if .Values.prometheus.backup.enabled }}
       - name: backup
         emptyDir: {}
+      {{- end }}
+      {{- if .Values.prometheus.thanos.enabled }}
+      - name: config-shared
+        emptyDir: {}
+      - name: thanos
+        secret:
+          secretName: '{{ template "name" . }}-thanos'
       {{- end }}
       nodeSelector:
 {{ toYaml .Values.prometheus.nodeSelector | indent 8 }}
